use_frameworks!

platform :ios, '8.0'

target 'MTSensorKit_Example' do
  pod 'MTSensorKit', :path => '../'

  target 'MTSensorKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
